# CircleCI configuration file
version: 2.1


orbs:
  python: circleci/python@2.1.1

jobs:
  test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  increase-version:
    executor: python/default
    steps:
      - checkout
      - run: pip install bumpversion
      - run: bumpversion patch
  publish:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: pip install twine && twine upload dist/* --non-interactive


workflows:
  build-and-test:
    jobs:
      - test
      - increase-version:
          requires:
            - test
      - publish:
        requires:
          - increase-version
        filters:
          branches:
            only: main