# CircleCI configuration file
version: 2.1


orbs:
  python: circleci/python@2.1.1
  base: dialogue/base@1.15.1
  release: dialogue/release@2.9.1

jobs:
  test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  increase-version:
    executor: python/default
    steps:
      - checkout
      - base/setup
      - release/bump_version
  publish:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: pip install twine && twine upload dist/* --non-interactive


workflows:
  build-and-test:
    jobs:
      - test
      - increase-version:
        type: approval
        requires:
          - test
      - publish:
        requires:
          - increase-version
        filters:
          branches:
            only:
              - main