# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
     - image: cimg/python:3.10.0
    branches:
      only:
        - main
    steps:
      - run: echo "Say hello to YAML!"

  build_and_test: # this can be any name you choose
    docker:
      # Primary container image where all steps run
      - image: cimg/python:3.10.0
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .